import type { DesignDirection, ProjectPlan } from "./planner";

export type GeneratedFile = {
  path: string;
  content: string;
  language: "tsx" | "ts" | "css" | "json" | "md" | "html";
};

export type BuildResult = {
  files: GeneratedFile[];
  provider: string;
  model?: string;
  warning?: string;
};

function esc(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

export function generateFilesStub(
  plan: ProjectPlan,
  design: DesignDirection
): GeneratedFile[] {
  const c = design.colors;
  const siteName = plan.brief.split(/[.!]/)[0]?.slice(0, 48)?.trim() || "Your App";
  const navPages = plan.pages.slice(0, 5);

  const globalsCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --primary: ${c.primary};\n  --background: ${c.background};\n  --foreground: ${c.foreground};\n}\n\nbody { background: var(--background); color: var(--foreground); }\n`;

  const layoutTsx = `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "${esc(siteName)}",\n  description: "${esc(plan.brief.slice(0, 160))}",\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body className="min-h-screen antialiased">{children}</body>\n    </html>\n  );\n}\n`;

  const navLinks = navPages
    .map((p) => `          <a href="${p.path}" className="text-sm opacity-80 hover:opacity-100">${p.name}</a>`)
    .join("\n");

  const featureCards = plan.features
    .filter((f) => f.priority === "mvp")
    .slice(0, 4)
    .map(
      (f) =>
        `        <div className="rounded-2xl border border-white/10 bg-white/5 p-6">\n          <h3 className="font-semibold text-lg mb-2">${esc(f.name)}</h3>\n          <p className="text-sm opacity-70">${esc(f.description)}</p>\n        </div>`
    )
    .join("\n");

  const pageTsx = `export default function HomePage() {\n  return (\n    <div className="min-h-screen" style={{ background: "${c.background}", color: "${c.foreground}" }}>\n      <header className="border-b border-white/10">\n        <div className="mx-auto max-w-6xl px-6 h-16 flex items-center justify-between">\n          <span className="font-semibold">${esc(siteName)}</span>\n          <nav className="hidden md:flex gap-6">\n${navLinks}\n          </nav>\n        </div>\n      </header>\n      <main className="mx-auto max-w-6xl px-6 pt-20 pb-16 text-center">\n        <p className="text-xs uppercase tracking-widest mb-4" style={{ color: "${c.accent}" }}>${esc(design.mood)}</p>\n        <h1 className="text-4xl md:text-6xl font-bold max-w-3xl mx-auto">${esc(siteName)}</h1>\n        <p className="mt-6 text-lg opacity-70 max-w-2xl mx-auto">${esc(plan.brief)}</p>\n        <a href="#features" className="inline-block mt-10 rounded-full px-6 py-3 text-sm font-semibold text-zinc-950" style={{ background: "${c.primary}" }}>Explore</a>\n        <section id="features" className="mt-16 grid md:grid-cols-2 gap-4 text-left">\n${featureCards}\n        </section>\n      </main>\n      <footer className="border-t border-white/10 py-8 text-center text-xs opacity-50">Built with Vireo</footer>\n    </div>\n  );\n}\n`;

  const packageJson = JSON.stringify(
    {
      name: "vireo-generated-app",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: { next: "^15.0.0", react: "^19.0.0", "react-dom": "^19.0.0" },
      devDependencies: {
        typescript: "^5.7.0",
        tailwindcss: "^3.4.17",
        postcss: "^8.4.49",
        autoprefixer: "^10.4.20",
        "@types/react": "^19.0.0",
        "@types/node": "^22.0.0",
      },
    },
    null,
    2
  );

  const readme = `# ${siteName}\n\n${plan.brief}\n\nGenerated by **Vireo**.\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`;

  return [
    { path: "package.json", content: packageJson, language: "json" },
    { path: "src/app/globals.css", content: globalsCss, language: "css" },
    { path: "src/app/layout.tsx", content: layoutTsx, language: "tsx" },
    { path: "src/app/page.tsx", content: pageTsx, language: "tsx" },
    { path: "README.md", content: readme, language: "md" },
  ];
}

export async function runBuild(
  plan: ProjectPlan,
  design: DesignDirection
): Promise<BuildResult> {
  const res = await fetch("/api/build", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ plan, design }),
  });
  if (!res.ok) {
    return { files: generateFilesStub(plan, design), provider: "stub", warning: `API ${res.status}` };
  }
  return res.json();
}
